### ISSUE TITLE
Template generation won't complete

### ISSUE THREAD

**Issue by stalinkay** [AddExtension/generator-joomla#14]
I'm getting the following stack output when trying to generate a joomla template. I'm running node v5.11.1. How can I resolve this?

```
? How do you license the project? GNU General Public License, version 2 or later
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open '/usr/local/lib/node_modules/generator-joomla/app/templates/.gitignore'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.readFileSync (fs.js:431:33)
    at _prepCopy (/usr/local/lib/node_modules/generator-joomla/node_modules/yeoman-generator/lib/actions/actions.js:37:17)
    at copy (/usr/local/lib/node_modules/generator-joomla/node_modules/yeoman-generator/lib/actions/actions.js:70:19)
    at module.exports.generators.Base.extend.writing (/usr/local/lib/node_modules/generator-joomla/app/index.js:252:8)
    at /usr/local/lib/node_modules/generator-joomla/node_modules/yeoman-generator/lib/base.js:409:16
    at tryOnImmediate (timers.js:534:15)
    at processImmediate [as _immediateCallback] (timers.js:514:5)
```

**Comment by stalinkay** [comment]
This is my current workaround.

`touch /usr/local//lib/node_modules/generator-joomla/app/templates/.gitignore
`
It seems the file is not installed during installation
`npm install -g generator-joomla`

**Comment by stalinkay** [comment]
I'm also getting the following error:

```
Running "imagemin:target" (imagemin) task
Fatal error: Cannot read property 'contents' of undefined
```

**Comment by fede91it** [comment]
And for the imagemin issue give a look here:
https://github.com/gruntjs/grunt-contrib-imagemin/issues/330
